#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/usbd,v 1.3 2004/10/07 13:55:26 mtm Exp $
#
# Made for FreeBSD 9.2
# Put this file in /etc/rc.d
# 
# In /etc/rc.conf, put callhome_enable="YES"

# PROVIDE: callhome
# REQUIRE: DAEMON
# BEFORE: LOGIN
# KEYWORD: nojail

. /etc/rc.subr

name="callhome"
rcvar=`set_rcvar`
command="/usr/local/bin/sshconnect.sh"
command_interpreter="yes"
command_args="&"

load_rc_config $name
run_rc_command "$1"
